run:
  timeout: 10m
  tests: true
  modules-download-mode: readonly
  go: '1.24'

linters:
  enable:
    # Default linters
    - errcheck        # Check for unchecked errors
    - gosimple        # Simplify code
    - govet           # Reports suspicious constructs
    - ineffassign     # Detect ineffectual assignments
    - staticcheck     # State of the art linter
    - unused          # Check for unused code

    # Additional important linters
    - gocyclo         # Cyclomatic complexity
    - gofmt           # Format code
    - goimports       # Check imports
    - misspell        # Find commonly misspelled words
    - goconst         # Find repeated strings that could be constants
    - unconvert       # Remove unnecessary type conversions
    - unparam         # Find unused function parameters
    - gosec           # Security checks
    - prealloc        # Find slice declarations that could be preallocated
    - exportloopref   # Check for loop variable references
    - noctx           # HTTP requests should use context
    - bodyclose       # Check HTTP response body is closed
    - sqlclose        # Check SQL rows/statements are closed
    - rowserrcheck    # Check SQL rows errors
    - dupl            # Code duplication
    - gocognit        # Cognitive complexity
    - gocritic        # Comprehensive linter
    - revive          # Fast, configurable linter
    - stylecheck      # Style checker
    - goprintffuncname # Printf-like function name check
    - nolintlint      # Ill-formed nolint directives
    - whitespace      # Whitespace issues

  disable:
    - exhaustive      # Can be too strict for switches
    - funlen          # Function length - too opinionated
    - lll             # Line length - handled by gofmt
    - wsl             # Whitespace linter - too strict
    - gomnd           # Magic numbers - too strict for tests
    - testpackage     # Separate test packages - not always needed

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.Rows).Close
      - (*database/sql.Stmt).Close

  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment  # Too strict, impacts readability

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true

  misspell:
    locale: US
    ignore-words:
      - traefik
      - oidc
      - keycloak

  unparam:
    check-exported: false

  gosec:
    excludes:
      - G104  # Audit errors not checked (errcheck handles this)
      - G404  # Random number generator (acceptable in tests)
    severity: medium
    confidence: medium

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
    dot-import-whitelist:
      - fmt
    initialisms: ["ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "JWT", "LHS", "QPS", "RAM", "RHS", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS", "OIDC", "PKCE", "CSRF", "HSTS", "CSP", "CORS"]

  gocritic:
    enabled-checks:
      - appendAssign
      - appendCombine
      - argOrder
      - assignOp
      - badCall
      - badCond
      - boolExprSimplify
      - builtinShadow
      - captLocal
      - caseOrder
      - commentFormatting
      - commentedOutCode
      - defaultCaseOrder
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - elseif
      - emptyFallthrough
      - equalFold
      - exitAfterDefer
      - flagDeref
      - flagName
      - hexLiteral
      - ifElseChain
      - indexAlloc
      - initClause
      - methodExprCall
      - nestingReduce
      - newDeref
      - offBy1
      - rangeExprCopy
      - rangeValCopy
      - regexpMust
      - singleCaseSwitch
      - sloppyLen
      - stringXbytes
      - switchTrue
      - typeAssertChain
      - typeSwitchVar
      - typeUnparen
      - underef
      - unlabelStmt
      - unlambda
      - unslice
      - valSwap
      - weakCond
      - wrapperFunc
      - yodaStyleExpr

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit
        - dupl
        - gosec
        - goconst
        - bodyclose
        - noctx
        - unparam
        - prealloc

    # Exclude test helper functions from complexity checks
    - path: test.*\.go
      linters:
        - gocyclo
        - gocognit
        - dupl

    # Exclude mocks from checks
    - path: mocks.*\.go
      linters:
        - unused
        - deadcode
        - gocritic
        - stylecheck

    # Known false positives
    - linters:
        - gosec
      text: "G404:"  # Random number generation in tests is fine

    # Exclude certain directories
    - path: vendor/
      linters:
        - all

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true
